# Generated by Django 3.1.5 on 2021-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.TextField(max_length=64)),
                ('priv', models.TextField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_hash',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_hash',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='r_pub',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='s_pub',
            field=models.TextField(max_length=64),
        ),
    ]
