# Generated by Django 3.1.5 on 2021-05-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0002_auto_20210503_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='previous_hash',
        ),
    ]
