# Generated by Django 3.1.5 on 2021-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0003_remove_transaction_previous_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
